apiVersion: v1
kind: Service
metadata:
  name: demo-web-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app: demo-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-web
  name: demo-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
      - image: webbutvecklinghelsingborg/gitops:v3
        name: demo-web
        ports:
        - containerPort: 80
