apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-deployment
spec:
  replicas: 8
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: demo-web
        image: webbutvecklinghelsingborg/gitops:latest
