patchesStrategicMerge:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: webbutvecklinghelsingborg/gitops
  newName: webbutvecklinghelsingborg/gitops
  newTag: dce4674e217b4ee8c0d8e3ecbde4bb7bcdecd551
