patchesStrategicMerge:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: webbutvecklinghelsingborg/gitops
  newName: webbutvecklinghelsingborg/gitops
  newTag: 2bca94d01ceff24700f9fa22155dad3ddb62139d
